force-app/main/default/objects/Habilidade__c/Habilidade__c.object-meta.xml
<CustomObject>
    <description>Objeto usado para armazenas as habilidades.</description>
    <label>Habilidade</label>
    <nameField>
        <label>Nome de Habilidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Habilidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Habilidade__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Habilidades</relationshipLabel>
    <relationshipName>Habilidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/HabilidadeContato__c.object-meta.xml
<CustomObject>
    <description>Usado para efetuar a junção entre os objetos Habilidade e Contato.</description>
    <label>Habilidade do Contato</label>
    <nameField>
        <displayFormat>HABIL-{0000}</displayFormat>
        <label>Habilidades do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Habilidades do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Habilidades do Contato</relationshipLabel>
    <relationshipName>HabilidadesContato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Habilidade__c.field-meta.xml
<CustomField>
    <fullName>Habilidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Habilidade</label>
    <referenceTo>Habilidade__c</referenceTo>
    <relationshipLabel>Habilidades do Contato</relationshipLabel>
    <relationshipName>HabilidadesContato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContactCreateTask.cls
global class ContactCreateTask {

    @InvocableMethod(label = 'Cria tarefa para o Contato')
    public static void ContactCreateTask(List<CreateTaskRequest> requests){
        System.debug('>>> requests:: ' + requests);
        
        
        List<Id> listContactId = new List<Id>();
        for(CreateTaskRequest request : requests){
            listContactId.add(request.contactId);
        }
        
	
		        
        List<HabilidadeContato__c> listaHabilidades = [SELECT Id, Contato__c, Habilidade__r.Name FROM HabilidadeContato__c];
        
       	Map<Id, List<String>> mapContatoHabilidades = new Map<Id, List<String>>();
        
        for(HabilidadeContato__c habilidade : listaHabilidades){
            if(mapContatoHabilidades.containsKey(habilidade.Contato__c)){
                mapContatoHabilidades.get(habilidade.Contato__c).add(habilidade.Habilidade__r.Name);
            }else{
                mapContatoHabilidades.put(habilidade.Contato__c, new List<String>{ habilidade.Habilidade__r.Name});
                
            }
        }

       createtask(requests, mapContatoHabilidades);
    }
    
    public static void createTask(List<CreateTaskRequest> requests, Map<Id, List<String>> mapContatoHabilidades){
        List<Task> taskToInsert = new List<Task>();
        
        for(CreateTaskRequest request : requests){
            Task tarefa = new Task();
            tarefa.Subject = request.subject;
            tarefa.WhoId = request.contactId;
            tarefa.OwnerId = request.ownerId;
            tarefa.Description = 'Por favor, avalie este herói. Suas habilidades sãoa as seguintes: '+ String.valueOf(mapContatoHabilidades.get(request.contactId));
            tarefa.Status = 'Open';
			
            taskToInsert.add(tarefa);
        }
        
        if(!taskToInsert.isEmpty()){ 
        	insert taskToInsert;
        }
    }
    global Class CreateTaskRequest{
        @InvocableVariable(required=true)
        global String contactId;
        @InvocableVariable()
        global String subject;
        @InvocableVariable(required=true)
        global String ownerId;
    }
}