force-app/main/default/objects/BatalhaContato__c/BatalhaContato__c.object-meta.xml
<CustomObject>
    <description>Objeto usado para associar as batalhas aos contatos</description>
    <label>Batalha do Contato</label>
    <nameField>
        <displayFormat>BC-{0000}</displayFormat>
        <label>Nome de Batalha do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batalhas do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BatalhaContato__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <description>Objeto para relacionar o contato com a batalha</description>
    <inlineHelpText>Objeto para relacionar o contato com a batalha</inlineHelpText>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Batalhas do Contato</relationshipLabel>
    <relationshipName>Batalhas_do_Contato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/NivelHeroi__c.field-meta.xml
<CustomField>
    <fullName>NivelHeroi__c</fullName>
    <description>Indique o nível atual do personagem.</description>
    <inlineHelpText>Selecione entre as opções dispostas qual o nível especifico de heroismo.</inlineHelpText>
    <label>Nível de Herói</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aspirante</fullName>
            </value>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Pleno</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/NomeGuerra__c.field-meta.xml
<CustomField>
    <fullName>NomeGuerra__c</fullName>
    <description>Indique como o personagem é conhecido de modo geral.
Ex.: Homem Aranha, Hulk...</description>
    <inlineHelpText>Indique como o personagem é conhecido de modo geral.
Ex.: Homem Aranha, Hulk...</inlineHelpText>
    <label>Nome de Guerra</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Heroi.recordType-meta.xml
<RecordType>
    <fullName>Heroi</fullName>
    <active>true</active>
    <label>Herói</label>
</RecordType>

force-app/main/default/objects/Habilidade__c/Habilidade__c.object-meta.xml
<CustomObject>
    <description>Objeto usado para armazenas as habilidades.</description>
    <label>Habilidade</label>
    <nameField>
        <label>Nome de Habilidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Habilidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Habilidade__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Habilidades</relationshipLabel>
    <relationshipName>Habilidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Habilidade__c/fields/NivelHabilidade__c.field-meta.xml
<CustomField>
    <fullName>NivelHabilidade__c</fullName>
    <description>Campo utilizado para armazenar o nivel referente a habilidade</description>
    <inlineHelpText>Campo utilizado para armazenar o nivel referente a habilidade</inlineHelpText>
    <label>Nivel Habilidade</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/HabilidadeContato__c.object-meta.xml
<CustomObject>
    <description>Usado para efetuar a junção entre os objetos Habilidade e Contato.</description>
    <label>Habilidade do Contato</label>
    <nameField>
        <displayFormat>HABIL-{0000}</displayFormat>
        <label>Habilidades do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Habilidades do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Habilidades do Contato</relationshipLabel>
    <relationshipName>HabilidadesContato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Habilidade__c.field-meta.xml
<CustomField>
    <fullName>Habilidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Habilidade</label>
    <referenceTo>Habilidade__c</referenceTo>
    <relationshipLabel>Habilidades do Contato</relationshipLabel>
    <relationshipName>HabilidadesContato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/NivelHabilidade__c.field-meta.xml
<CustomField>
    <fullName>NivelHabilidade__c</fullName>
    <description>Campo para armazenar o nivel de habilidade do contato</description>
    <inlineHelpText>Selecione de 0 a 100 para definir o nivel de habilidade do contato atual</inlineHelpText>
    <label>Nivel Habilidade</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GetAvailableHeroesIS.cls
@RestResource(urlMapping='/marvel/availableheroes/*')
global class GetAvailableHeroesIS {

    @HttpGet
    global static AvailableHeroes doGet(){
        Map<String, Hero> mapHerois = new Map<String, Hero>();
        List<HabilidadeContato__c> listHbContato = new List<HabilidadeContato__c>();
        
        String habilidadeParam = RestContext.request.params.get('habilidade');
        String nivelParam = RestContext.request.params.get('nivel');
        
        String dynamicQuery = 'SELECT id, Contato__r.NomeGuerra__c, Contato__r.NivelHeroi__c, Habilidade__r.Name, NivelHabilidade__c FROM HabilidadeContato__c where Contato__r.RecordType.DeveloperName = \'Heroi\' AND Contato__c NOT IN (Select Contato__c from BatalhaContato__c)';
        
        if(!String.isBlank(habilidadeParam)){
            List<String> habilidadesParam = habilidadeParam.split(',');
            dynamicQuery += ' AND Habilidade__r.Name IN :habilidadesParam';
        }if(!String.isBlank(nivelParam)){
            List<String> niveisParam = nivelParam.split(',');
            dynamicQuery += ' AND Contato__r.NivelHeroi__c IN :niveisParam';
        }
        
        listHbContato = Database.query(dynamicQuery);
        
        for(HabilidadeContato__c habilidadeContato : listHbContato){
            Skill habilidade = new Skill(habilidadeContato.Habilidade__r.Name, String.valueOf(habilidadeContato.NivelHabilidade__c));
         	Hero heroi;
            
            if( !mapHerois.containsKey(habilidadeContato.Contato__r.NomeGuerra__c)){
                heroi = new Hero();
                heroi.nome = HabilidadeContato.Contato__r.NomeGuerra__c;
                heroi.nivel = HabilidadeContato.Contato__r.NivelHeroi__c;
                heroi.habilidades = new List<Skill>{ habilidade};
            }else{
                heroi = mapHerois.get(habilidadeContato.Contato__r.NomeGuerra__c);
                heroi.habilidades.add(habilidade);
            }
            
            mapHerois.put(habilidadeContato.Contato__r.NomeGuerra__c, heroi);

         }
        
       return new AvailableHeroes(mapHerois.values());
    }
    
    global class AvailableHeroes{
        public List<Hero> herois;
        public Integer total;
        
        AvailableHeroes(List<Hero> herois){
            this.herois = herois;
            this.total = herois.size();
        }
        
    }
    global class Hero{
        public String nome;
        public String nivel;
        public List<Skill> habilidades;
    }
    global class Skill{
        public String nome;
        public String nivel;
        
        Skill(String nome, String nivel){
            this.nome = nome;
            this.nivel = nivel != null ? nivel : 'Nao avaliado';
        }
            
    }
}