force-app/main/default/objects/Batalha__c/Batalha__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as batalhas</description>
    <label>Batalha</label>
    <nameField>
        <label>Nome de Batalha</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batalhas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BatalhaContato__c/BatalhaContato__c.object-meta.xml
<CustomObject>
    <description>Objeto usado para associar as batalhas aos contatos</description>
    <label>Batalha do Contato</label>
    <nameField>
        <displayFormat>BC-{0000}</displayFormat>
        <label>Nome de Batalha do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batalhas do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BatalhaContato__c/fields/Batalha__c.field-meta.xml
<CustomField>
    <fullName>Batalha__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Objeto para relacionar a Batalha</description>
    <inlineHelpText>Objeto para relacionar a Batalha</inlineHelpText>
    <label>Batalha</label>
    <referenceTo>Batalha__c</referenceTo>
    <relationshipLabel>Batalhas do Contato</relationshipLabel>
    <relationshipName>Batalhas_do_Contato</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BatalhaContato__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <description>Objeto para relacionar o contato com a batalha</description>
    <inlineHelpText>Objeto para relacionar o contato com a batalha</inlineHelpText>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Batalhas do Contato</relationshipLabel>
    <relationshipName>Batalhas_do_Contato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FeedbackTreinamento__c.field-meta.xml
<CustomField>
    <fullName>FeedbackTreinamento__c</fullName>
    <description>Campo para informar todas informações sobre o treinamento do possivel Heroi.</description>
    <inlineHelpText>Campo para informar todas informações sobre o treinamento do possivel Heroi.</inlineHelpText>
    <label>Feedback Treinamento</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/NivelHeroi__c.field-meta.xml
<CustomField>
    <fullName>NivelHeroi__c</fullName>
    <description>Indique o nível atual do personagem.</description>
    <inlineHelpText>Selecione entre as opções dispostas qual o nível especifico de heroismo.</inlineHelpText>
    <label>Nível de Herói</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aspirante</fullName>
            </value>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Pleno</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/NomeGuerra__c.field-meta.xml
<CustomField>
    <fullName>NomeGuerra__c</fullName>
    <description>Indique como o personagem é conhecido de modo geral.
Ex.: Homem Aranha, Hulk...</description>
    <inlineHelpText>Indique como o personagem é conhecido de modo geral.
Ex.: Homem Aranha, Hulk...</inlineHelpText>
    <label>Nome de Guerra</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/StatusCandidato__c.field-meta.xml
<CustomField>
    <fullName>StatusCandidato__c</fullName>
    <description>Exibe os status do candidato</description>
    <inlineHelpText>Selecione uma das opções para referenciar o status atual do candidato</inlineHelpText>
    <label>Status Candidato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em Análise</fullName>
                <default>true</default>
                <label>Em Análise</label>
            </value>
            <value>
                <fullName>Reprovado na Análise</fullName>
            </value>
            <value>
                <fullName>Aguardando Aprovação p/ Treinamento</fullName>
            </value>
            <value>
                <fullName>Reprovado na Análise do Gestor</fullName>
            </value>
            <value>
                <fullName>Em Treinamento</fullName>
            </value>
            <value>
                <fullName>Reprovado no Treinamento</fullName>
            </value>
            <value>
                <fullName>Aprovado pelo Treinamento</fullName>
            </value>
            <value>
                <fullName>Aprovado Direto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Habilidade__c/Habilidade__c.object-meta.xml
<CustomObject>
    <description>Objeto usado para armazenas as habilidades.</description>
    <label>Habilidade</label>
    <nameField>
        <label>Nome de Habilidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Habilidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/HabilidadeContato__c.object-meta.xml
<CustomObject>
    <description>Usado para efetuar a junção entre os objetos Habilidade e Contato.</description>
    <label>Habilidade do Contato</label>
    <nameField>
        <displayFormat>HABIL-{0000}</displayFormat>
        <label>Habilidades do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Habilidades do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Habilidades do Contato</relationshipLabel>
    <relationshipName>HabilidadesContato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Habilidade__c.field-meta.xml
<CustomField>
    <fullName>Habilidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Habilidade</label>
    <referenceTo>Habilidade__c</referenceTo>
    <relationshipLabel>Habilidades do Contato</relationshipLabel>
    <relationshipName>HabilidadesContato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/NivelHabilidade__c.field-meta.xml
<CustomField>
    <fullName>NivelHabilidade__c</fullName>
    <description>Campo para armazenar o nivel de habilidade do contato</description>
    <inlineHelpText>Selecione de 0 a 100 para definir o nivel de habilidade do contato atual</inlineHelpText>
    <label>Nivel Habilidade</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/HeroiPDFWithApexController.cls
public with sharing class HeroiPDFWithApexController {

    public Contact contato {get; set;}

    public HeroiPDFWithApexController() {
        Id contactId = ApexPages.currentPage().getParameters().get('id');

        this.contato = [select id, Name, NomeGuerra__c, NivelHeroi__c, StatusCandidato__c, FeedbackTreinamento__c,
                        (select Habilidade__r.Name, NivelHabilidade__c from HabilidadesContato__r order by NivelHabilidade__c),
                        (select Id, Batalha__r.Name, Batalha__r.Descricao__c, Batalha__r.DataInicio__c, Batalha__r.DataTermino__c from Batalhas_do_Contato__r)
                        from Contact where Id = :contactId];


    }
 

}