force-app/main/default/objects/Lead/fields/NivelHeroi__c.field-meta.xml
<CustomField>
    <fullName>NivelHeroi__c</fullName>
    <description>Indique o nível atual do personagem.</description>
    <inlineHelpText>Selecione entre as opções dispostas qual o nível especifico de heroismo.</inlineHelpText>
    <label>Nível de Herói</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aspirante</fullName>
            </value>
            <value>
                <fullName>Júnior</fullName>
            </value>
            <value>
                <fullName>Pleno</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/NomeGuerra__c.field-meta.xml
<CustomField>
    <fullName>NomeGuerra__c</fullName>
    <description>Indique como o personagem é conhecido de modo geral.
Ex.: Homem Aranha, Hulk...</description>
    <inlineHelpText>Indique como o personagem é conhecido de modo geral.
Ex.: Homem Aranha, Hulk...</inlineHelpText>
    <label>Nome de Guerra</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/MostraCallOut.cls
public class MostraCallOut {

    public static void doCallOut(){
        
        Lead lead = new Lead();
        lead.FirstName = 'Bruce';
        lead.LastName = 'Wayne';
        lead.NomeGuerra__c = 'Batman';
        lead.Email  = 'batman' + '@marvel.com';
        lead.LeadSource  = 'Importado pela Marvel API';
        lead.NivelHeroi__c = 'Aspirante';
        
        insert lead;
        
        CallOutMarvel.getPersonagens();
    }
}