force-app/main/default/objects/Contact/fields/NivelHeroi__c.field-meta.xml
<CustomField>
    <fullName>NivelHeroi__c</fullName>
    <description>Indique o nível atual do personagem.</description>
    <inlineHelpText>Selecione entre as opções dispostas qual o nível especifico de heroismo.</inlineHelpText>
    <label>Nível de Herói</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aspirante</fullName>
            </value>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Pleno</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Heroi.recordType-meta.xml
<RecordType>
    <fullName>Heroi</fullName>
    <active>true</active>
    <label>Herói</label>
</RecordType>

force-app/main/default/objects/HabilidadeContato__c/HabilidadeContato__c.object-meta.xml
<CustomObject>
    <description>Usado para efetuar a junção entre os objetos Habilidade e Contato.</description>
    <label>Habilidade do Contato</label>
    <nameField>
        <displayFormat>HABIL-{0000}</displayFormat>
        <label>Habilidades do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Habilidades do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/fields/NivelHabilidade__c.field-meta.xml
<CustomField>
    <fullName>NivelHabilidade__c</fullName>
    <description>Campo para armazenar o nivel de habilidade do contato</description>
    <inlineHelpText>Selecione de 0 a 100 para definir o nivel de habilidade do contato atual</inlineHelpText>
    <label>Nivel Habilidade</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/IdentificarNivelHeroiFlow.cls
global class IdentificarNivelHeroiFlow {

    @InvocableMethod(label='Identifica Nivel do Heroi')
    public static void identificaNivelHeroi(List<ContactRequest> requests){
        
        List<Contact> contatos = new List<Contact>();
        
        for(ContactRequest request : requests){
            Decimal media = 0;
            Decimal somaLevel = 0;
            String nivel = '';
            
            for(HabilidadeContato__c habilidadeContato : request.habilidadesContato){
                
                if(habilidadeContato.NivelHabilidade__c == null){
                    habilidadeContato.NivelHabilidade__c = 10;
     
                }
                if(habilidadeContato != null)
                	somaLevel += HabilidadeContato.NivelHabilidade__c;
            }
            
            media = somaLevel/request.habilidadesContato.size();
            
            if(media >= 80){
                nivel = 'Senior';
            }
            else if(media >= 40){
                nivel = 'Pleno';
            }
            else{
                nivel = 'Junior';
            }
            
            //contatos.add(new Contact(Id = request.contactId, NivelHeroi__c = nivel));
            request.contact.NivelHeroi__c = nivel;
            contatos.add(request.contact);
        }
        
        update contatos;
    }
    
    global class ContactRequest{
        @InvocableVariable(required=true)
        global Contact contact;
        @InvocableVariable(required=true) 
        global List<HabilidadeContato__c> habilidadesContato;
    }
}