force-app/main/default/objects/Contact/fields/NomeGuerra__c.field-meta.xml
<CustomField>
    <fullName>NomeGuerra__c</fullName>
    <description>Indique como o personagem é conhecido de modo geral.
Ex.: Homem Aranha, Hulk...</description>
    <inlineHelpText>Indique como o personagem é conhecido de modo geral.
Ex.: Homem Aranha, Hulk...</inlineHelpText>
    <label>Nome de Guerra</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/StatusCandidato__c.field-meta.xml
<CustomField>
    <fullName>StatusCandidato__c</fullName>
    <description>Exibe os status do candidato</description>
    <inlineHelpText>Selecione uma das opções para referenciar o status atual do candidato</inlineHelpText>
    <label>Status Candidato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em Análise</fullName>
                <default>true</default>
                <label>Em Análise</label>
            </value>
            <value>
                <fullName>Reprovado na Análise</fullName>
            </value>
            <value>
                <fullName>Aguardando Aprovação p/ Treinamento</fullName>
            </value>
            <value>
                <fullName>Reprovado na Análise do Gestor</fullName>
            </value>
            <value>
                <fullName>Em Treinamento</fullName>
            </value>
            <value>
                <fullName>Reprovado no Treinamento</fullName>
            </value>
            <value>
                <fullName>Aprovado pelo Treinamento</fullName>
            </value>
            <value>
                <fullName>Aprovado Direto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Habilidade__c/Habilidade__c.object-meta.xml
<CustomObject>
    <description>Objeto usado para armazenas as habilidades.</description>
    <label>Habilidade</label>
    <nameField>
        <label>Nome de Habilidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Habilidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Habilidade__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Habilidades</relationshipLabel>
    <relationshipName>Habilidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Habilidade__c/fields/NivelHabilidade__c.field-meta.xml
<CustomField>
    <fullName>NivelHabilidade__c</fullName>
    <description>Campo utilizado para armazenar o nivel referente a habilidade</description>
    <inlineHelpText>Campo utilizado para armazenar o nivel referente a habilidade</inlineHelpText>
    <label>Nivel Habilidade</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/HabilidadeContato__c.object-meta.xml
<CustomObject>
    <description>Usado para efetuar a junção entre os objetos Habilidade e Contato.</description>
    <label>Habilidade do Contato</label>
    <nameField>
        <displayFormat>HABIL-{0000}</displayFormat>
        <label>Habilidades do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Habilidades do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Habilidades do Contato</relationshipLabel>
    <relationshipName>HabilidadesContato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Habilidade__c.field-meta.xml
<CustomField>
    <fullName>Habilidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Habilidade</label>
    <referenceTo>Habilidade__c</referenceTo>
    <relationshipLabel>Habilidades do Contato</relationshipLabel>
    <relationshipName>HabilidadesContato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/NivelHabilidade__c.field-meta.xml
<CustomField>
    <fullName>NivelHabilidade__c</fullName>
    <description>Campo para armazenar o nivel de habilidade do contato</description>
    <inlineHelpText>Selecione de 0 a 100 para definir o nivel de habilidade do contato atual</inlineHelpText>
    <label>Nivel Habilidade</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Ranking__c.field-meta.xml
<CustomField>
    <fullName>Ranking__c</fullName>
    <description>Usado para indicar a posição da habilidade ante o Ranking de habilidades.</description>
    <inlineHelpText>Usado para indicar a posição da habilidade ante o Ranking de habilidades.</inlineHelpText>
    <label>Ranking</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AtualizaRankingHabilidadeTriggerTest.cls
@isTest
public class AtualizaRankingHabilidadeTriggerTest {
 
    @testSetup
    public static void setup(){
        
        Contact contato = new Contact(
        	firstName = 'Matt',
            lastName = 'Murdock',
            NomeGuerra__c = 'Daredevil',
            StatusCandidato__c = 'Aprovado Direto'
        );
        Contact contato2 = new Contact(
        	firstName = 'Frank',
            lastName = 'Castle',
            NomeGuerra__c = 'Punisher',
            StatusCandidato__c = 'Em Treinamento'
        );
        
        List<Contact> contatos = new List<Contact> {contato, contato2};
        insert contatos;
        
        Habilidade__c visaoSensorial = new Habilidade__c(Name = 'Visão Sensorial');
        Habilidade__c resistencia = new Habilidade__c(Name = 'Resistência');
        
        List<Habilidade__c> habilidades = new List<Habilidade__c> {visaoSensorial, resistencia};
            
        insert habilidades;
        
        HabilidadeContato__c habilidadeContato1 = new HabilidadeContato__c();
        habilidadeContato1.Contato__c = contato.id;
        habilidadeContato1.Habilidade__c = visaoSensorial.id;
        habilidadeContato1.NivelHabilidade__c = 90;
        
        HabilidadeContato__c habilidadeContato2= new HabilidadeContato__c();
        habilidadeContato2.Contato__c = contato.id;
        habilidadeContato2.Habilidade__c = resistencia.id;
        habilidadeContato2.NivelHabilidade__c = 66;
        
        HabilidadeContato__c habilidadeContato3 = new HabilidadeContato__c();
        habilidadeContato3.Contato__c = contato2.id;
        habilidadeContato3.Habilidade__c = visaoSensorial.id;
        habilidadeContato3.NivelHabilidade__c = 10;
        
        HabilidadeContato__c habilidadeContato4= new HabilidadeContato__c();
        habilidadeContato4.Contato__c = contato2.id;
        habilidadeContato4.Habilidade__c = resistencia.id;
        habilidadeContato4.NivelHabilidade__c = 45;
        
        List<HabilidadeContato__c> habilidadesContato = new List<HabilidadeContato__c> {habilidadeContato1, habilidadeContato2, habilidadeContato3, habilidadeContato4};
        insert habilidadesContato;

    }
    
    @isTest
    public static void validaNovoRankingAfterInsert(){
        
        List<HabilidadeContato__c> habilidadesContato = [SELECT HABILIDADE__R.NAME, NAME
                                                        FROM HABILIDADECONTATO__C
                                                        WHERE CONTATO__R.NOMEGUERRA__C = 'Daredevil'];
        
        System.assertEquals(2, habilidadesContato.size());
        
        for(HabilidadeContato__c habilidadeContato : habilidadesContato){
            switch on habilidadeContato.Name{
                when 'Visão Sensorial'{
                    System.assertEquals(1, habilidadeContato.Ranking__c);
                }
                when 'Resistência'{ 
					System.assertEquals(2, habilidadeContato.Ranking__c);
                }
            }
        }
    }
}