force-app/main/default/objects/Contact/fields/NomeGuerra__c.field-meta.xml
<CustomField>
    <fullName>NomeGuerra__c</fullName>
    <description>Indique como o personagem é conhecido de modo geral.
Ex.: Homem Aranha, Hulk...</description>
    <inlineHelpText>Indique como o personagem é conhecido de modo geral.
Ex.: Homem Aranha, Hulk...</inlineHelpText>
    <label>Nome de Guerra</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Habilidade__c/Habilidade__c.object-meta.xml
<CustomObject>
    <description>Objeto usado para armazenas as habilidades.</description>
    <label>Habilidade</label>
    <nameField>
        <label>Nome de Habilidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Habilidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Habilidade__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Habilidades</relationshipLabel>
    <relationshipName>Habilidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Habilidade__c/fields/NivelHabilidade__c.field-meta.xml
<CustomField>
    <fullName>NivelHabilidade__c</fullName>
    <description>Campo utilizado para armazenar o nivel referente a habilidade</description>
    <inlineHelpText>Campo utilizado para armazenar o nivel referente a habilidade</inlineHelpText>
    <label>Nivel Habilidade</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/HabilidadeContato__c.object-meta.xml
<CustomObject>
    <description>Usado para efetuar a junção entre os objetos Habilidade e Contato.</description>
    <label>Habilidade do Contato</label>
    <nameField>
        <displayFormat>HABIL-{0000}</displayFormat>
        <label>Habilidades do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Habilidades do Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Habilidades do Contato</relationshipLabel>
    <relationshipName>HabilidadesContato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Habilidade__c.field-meta.xml
<CustomField>
    <fullName>Habilidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Habilidade</label>
    <referenceTo>Habilidade__c</referenceTo>
    <relationshipLabel>Habilidades do Contato</relationshipLabel>
    <relationshipName>HabilidadesContato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/NivelHabilidade__c.field-meta.xml
<CustomField>
    <fullName>NivelHabilidade__c</fullName>
    <description>Campo para armazenar o nivel de habilidade do contato</description>
    <inlineHelpText>Selecione de 0 a 100 para definir o nivel de habilidade do contato atual</inlineHelpText>
    <label>Nivel Habilidade</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EstudoSOQL.cls
public class EstudoSOQL {

    public static List<Contact> getAllContacts(){
        List<Contact> contatos = [SELECT id, NomeGuerra__c, Name FROM Contact];
        
        return contatos;
    }
    
    public static Contact getContactById(Id contatoId){
        Contact contato = [SELECT Id, Name, NomeGuerra__c FROM Contact where Id = :contatoId];
        
        return contato;
    }
    
    public static Map<String, Decimal> getAvgByContact(){
        AggregateResult[] result = [SELECT Contato__r.NomeGuerra__c NomeDeGuerra, AVG(NivelHabilidade__c) mediaLevel
                                    FROM HabilidadeContato__c 
									GROUP BY Contato__r.NomeGuerra__c
									HAVING AVG(NivelHabilidade__c) > 0 Order BY AVG(NivelHabilidade__c) DESC];
        Map<String, Decimal> mapa = new Map<String, Decimal>();
        
        for(AggregateResult resultado : result){
            String nomeDeGuerra = (String) resultado.get('NomeDeGuerra');
            Decimal mediaLevel = (Decimal) resultado.get('mediaLevel');
            
            mapa.put(nomeDeGuerra, mediaLevel);
        }
        
        return mapa;
    }
    
    public static List<HabilidadeContato__c> getHabilidadesByContatoOrHabilidade(String nomeDeGuerra, String nomeHabilidade){
    	String query = 'SELECT Habilidade__r.Name, NivelHabilidade__c, Contato__r.NomeGuerra__c FROM HabilidadeContato__c WHERE ';
        
        
        if(!String.isEmpty(nomeDeGuerra)){
            query += 'Contato__r.NomeGuerra__c = :nomeDeGuerra';
        }else{
            query += 'Habilidade__r.Name = :nomeHabilidade';
        }
        List<HabilidadeContato__c> habilidadesDoContato = DataBase.query(query);

        return habilidadesDoContato;
        
    }
    
    
    
    
    
    
    
    
}